export const POST_ADD = 'POST_ADD';
export const POST_TOGGLE_LIKE = 'POST_TOGGLE_LIKE';
export const POST_TOGGLE_REPOST = 'POST_TOGGLE_REPOST';
export const POST_CLICK_NEW_POST_NOTIFICATION = 'POST_CLICK_NEW_POST_NOTIFICATION';

export const USER_SET_NAME = 'USER_SET_NAME';
export const USER_SET_HANDLE = 'USER_SET_HANDLE';
export const USER_SET_PROFILE_PHOTO_URL = 'USER_SET_PROFILE_PHOTO_URL';
